# Generated by Django 5.2.8 on 2025-11-12 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.BigAutoField(primary_key=True, serialize=False)),
                ('eventslug', models.CharField(db_index=True, help_text='URL-friendly event identifier', max_length=255)),
                ('platformeventid', models.BigIntegerField(db_index=True, help_text='Event ID on the platform (e.g., PolyMarket)')),
                ('title', models.CharField(help_text='Event title', max_length=500)),
                ('description', models.TextField(help_text='Event description')),
                ('liquidity', models.DecimalField(decimal_places=2, help_text='Total liquidity in USD', max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, help_text='Total trading volume in USD', max_digits=20)),
                ('openInterest', models.DecimalField(db_column='openInterest', decimal_places=2, help_text='Open interest in USD', max_digits=20)),
                ('marketcreatedat', models.DateTimeField(help_text='When market was created on platform')),
                ('marketupdatedat', models.DateTimeField(help_text='When market was last updated on platform')),
                ('competitive', models.DecimalField(decimal_places=6, help_text='Competitive metric/score', max_digits=10)),
                ('negrisk', models.SmallIntegerField(help_text='Negative risk indicator (0/1)')),
                ('startdate', models.DateTimeField(help_text='Event start date')),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now, help_text='Record creation date')),
                ('platform', models.CharField(db_index=True, default='polymarket', help_text='Trading platform', max_length=50)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-marketcreatedat'],
                'indexes': [models.Index(fields=['eventslug'], name='events_eventsl_12e1de_idx'), models.Index(fields=['platformeventid'], name='events_platfor_1053b3_idx'), models.Index(fields=['platform'], name='events_platfor_dd01e5_idx'), models.Index(fields=['startdate'], name='events_startda_871a4d_idx')],
            },
        ),
    ]
