# Generated by Django 5.2.8 on 2025-11-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventslug',
            field=models.CharField(db_index=True, help_text='URL-friendly event identifier', max_length=255, unique=True),
        ),
    ]
