# Generated by Django 5.2.8 on 2025-12-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_eventslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enddate',
            field=models.DateTimeField(blank=True, help_text='Event end date', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Event tags in JSON format'),
        ),
    ]
