# Generated by Django 5.2.8 on 2025-11-12 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('marketsid', models.BigAutoField(primary_key=True, serialize=False)),
                ('marketid', models.BigIntegerField(db_index=True, help_text='Market identifier')),
                ('marketslug', models.CharField(db_index=True, help_text='URL-friendly market identifier', max_length=255)),
                ('platformmarketid', models.CharField(db_index=True, help_text='Market ID on the platform', max_length=255)),
                ('question', models.TextField(help_text='Market question/prediction')),
                ('startdate', models.DateTimeField(help_text='Market start date')),
                ('enddate', models.DateTimeField(help_text='Market end date')),
                ('marketcreatedat', models.DateTimeField(help_text='When market was created on platform')),
                ('closedtime', models.DateTimeField(blank=True, help_text='When market was closed', null=True)),
                ('volume', models.DecimalField(decimal_places=2, help_text='Trading volume in USD', max_digits=20)),
                ('liquidity', models.DecimalField(decimal_places=2, help_text='Market liquidity in USD', max_digits=20)),
                ('createdat', models.DateTimeField(auto_now_add=True, help_text='When record was created')),
                ('lastupdatedat', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('platform', models.CharField(db_index=True, default='polymarket', help_text='Trading platform', max_length=50)),
                ('eventsid', models.ForeignKey(db_column='eventsid', help_text='Event this market belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='events.event')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'db_table': 'markets',
                'ordering': ['-marketcreatedat'],
                'indexes': [models.Index(fields=['eventsid', 'marketid'], name='markets_eventsi_af3b0a_idx'), models.Index(fields=['marketslug'], name='markets_markets_913aaf_idx'), models.Index(fields=['platformmarketid'], name='markets_platfor_d80c1a_idx'), models.Index(fields=['platform'], name='markets_platfor_7a6893_idx'), models.Index(fields=['startdate', 'enddate'], name='markets_startda_d2eaf9_idx')],
            },
        ),
    ]
