# Generated by Django 5.2.8 on 2025-11-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='platformmarketid',
            field=models.CharField(db_index=True, help_text='Market ID on the platform', max_length=255, unique=True),
        ),
    ]
