# Generated by Django 5.2.8 on 2025-12-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_market_platformmarketid'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='competitive',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Competitive metric/score', max_digits=10, null=True),
        ),
    ]
