# Generated by Django 5.2.8 on 2025-11-25 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchid', models.BigAutoField(primary_key=True, serialize=False)),
                ('latestfetchedtime', models.DateTimeField(help_text='Latest trade timestamp that was fetched')),
                ('isactive', models.SmallIntegerField(db_index=True, default=1, help_text='Batch status (0=inactive, 1=active)')),
                ('createdat', models.DateTimeField(auto_now_add=True, help_text='When batch record was created')),
                ('lastupdatedat', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('marketsid', models.ForeignKey(db_column='marketsid', help_text='Market this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='trade_batches', to='markets.market')),
                ('walletsid', models.ForeignKey(db_column='walletsid', help_text='Wallet this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='trade_batches', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'batches',
                'ordering': ['-lastupdatedat'],
                'indexes': [models.Index(fields=['walletsid', 'marketsid'], name='batches_wallets_7844dc_idx'), models.Index(fields=['isactive'], name='batches_isactiv_56d6a1_idx'), models.Index(fields=['latestfetchedtime'], name='batches_latestf_0663a1_idx')],
                'unique_together': {('walletsid', 'marketsid')},
            },
        ),
    ]
