# Generated by Django 5.2.8 on 2025-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='batch',
            name='batches_isactiv_56d6a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='batch',
            name='batches_latestf_0663a1_idx',
        ),
        migrations.AlterField(
            model_name='batch',
            name='isactive',
            field=models.SmallIntegerField(default=1, help_text='Batch status (0=inactive, 1=active)'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='latestfetchedtime',
            field=models.DateTimeField(blank=True, help_text='Latest trade timestamp that was fetched', null=True),
        ),
    ]
