# Generated by Django 5.2.8 on 2025-11-27 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_market_platformmarketid'),
        ('trades', '0002_remove_batch_batches_isactiv_56d6a1_idx_and_more'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('tradeid', models.BigAutoField(primary_key=True, serialize=False)),
                ('conditionid', models.CharField(db_index=True, help_text='Platform market ID (condition ID from Polymarket)', max_length=255)),
                ('tradetype', models.SmallIntegerField(choices=[(1, 'BUY'), (2, 'SELL'), (3, 'MERGE'), (4, 'SPLIT'), (5, 'REDEEM')], db_index=True, help_text='Type of aggregated trade')),
                ('outcome', models.CharField(default='', help_text='Outcome (Yes/No/empty for MERGE/SPLIT/REDEEM)', max_length=100)),
                ('totalshares', models.DecimalField(decimal_places=6, help_text='Net shares change (+ve for buy, -ve for sell)', max_digits=20)),
                ('totalamount', models.DecimalField(decimal_places=2, help_text='Net amount change (-ve for buy, +ve for sell)', max_digits=20)),
                ('tradedate', models.DateField(db_index=True, help_text='Date of trades (for daily aggregation)')),
                ('transactioncount', models.IntegerField(default=1, help_text='Number of individual transactions aggregated')),
                ('createdat', models.DateTimeField(auto_now_add=True, help_text='When trade record was created')),
                ('lastupdatedat', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('marketsid', models.ForeignKey(db_column='marketsid', help_text='Market these trades belong to', on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='markets.market')),
                ('walletsid', models.ForeignKey(db_column='walletsid', help_text='Wallet that made these trades', on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'trades',
                'ordering': ['-tradedate', '-lastupdatedat'],
                'indexes': [models.Index(fields=['walletsid', 'marketsid', 'tradedate'], name='trades_wallets_748650_idx'), models.Index(fields=['tradetype', 'tradedate'], name='trades_tradety_5bca62_idx'), models.Index(fields=['conditionid'], name='trades_conditi_edbb69_idx'), models.Index(fields=['walletsid', 'tradetype'], name='trades_wallets_427209_idx')],
                'unique_together': {('walletsid', 'marketsid', 'tradetype', 'outcome', 'tradedate')},
            },
        ),
    ]
