# Generated by Django 5.2.8 on 2025-11-27 18:09

from django.db import migrations, models


def convert_timestamps_to_epoch(apps, schema_editor):
    """Convert existing timestamp values to epoch seconds"""
    db_alias = schema_editor.connection.alias
    
    # Use raw SQL to convert timestamps to epoch
    with schema_editor.connection.cursor() as cursor:
        # First, add a temporary column for the epoch values
        cursor.execute("""
            ALTER TABLE batches 
            ADD COLUMN latestfetchedtime_epoch BIGINT;
        """)
        
        # Convert existing timestamps to epoch and store in new column
        cursor.execute("""
            UPDATE batches 
            SET latestfetchedtime_epoch = EXTRACT(epoch FROM latestfetchedtime)::BIGINT 
            WHERE latestfetchedtime IS NOT NULL;
        """)
        
        # Drop the old column
        cursor.execute("""
            ALTER TABLE batches 
            DROP COLUMN latestfetchedtime;
        """)
        
        # Rename the new column to the original name
        cursor.execute("""
            ALTER TABLE batches 
            RENAME COLUMN latestfetchedtime_epoch TO latestfetchedtime;
        """)


def reverse_epoch_to_timestamps(apps, schema_editor):
    """Reverse operation: convert epoch back to timestamps"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # Add temporary timestamp column
        cursor.execute("""
            ALTER TABLE batches 
            ADD COLUMN latestfetchedtime_ts TIMESTAMP WITH TIME ZONE;
        """)
        
        # Convert epoch back to timestamp
        cursor.execute("""
            UPDATE batches 
            SET latestfetchedtime_ts = TO_TIMESTAMP(latestfetchedtime)
            WHERE latestfetchedtime IS NOT NULL;
        """)
        
        # Drop epoch column and rename timestamp column
        cursor.execute("""
            ALTER TABLE batches 
            DROP COLUMN latestfetchedtime;
        """)
        
        cursor.execute("""
            ALTER TABLE batches 
            RENAME COLUMN latestfetchedtime_ts TO latestfetchedtime;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade'),
    ]

    operations = [
        migrations.RunPython(
            convert_timestamps_to_epoch,
            reverse_epoch_to_timestamps,
        ),
    ]
