# Generated by Django 5.2.8 on 2025-12-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_batch_latestfetchedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='latestfetchedtime',
            field=models.BigIntegerField(blank=True, help_text='Latest trade timestamp that was fetched (epoch seconds)', null=True),
        ),
    ]
