# Generated by Django 5.2.8 on 2025-11-12 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('positionid', models.BigAutoField(primary_key=True, serialize=False)),
                ('walletid', models.CharField(db_index=True, help_text='Wallet address of position holder', max_length=255)),
                ('outcome', models.CharField(help_text='Predicted outcome (Yes/No/etc.)', max_length=100)),
                ('positionstatus', models.SmallIntegerField(db_index=True, help_text='Position status (0=closed, 1=open, etc.)')),
                ('totalshares', models.DecimalField(decimal_places=6, help_text='Total shares held', max_digits=20)),
                ('averageentryprice', models.DecimalField(decimal_places=6, help_text='Average entry price per share', max_digits=10)),
                ('amountspent', models.DecimalField(decimal_places=2, help_text='Total amount spent in USD', max_digits=20)),
                ('amounttakenout', models.DecimalField(decimal_places=2, help_text='Amount withdrawn/cashed out in USD', max_digits=20)),
                ('amountremaining', models.DecimalField(decimal_places=2, help_text='Amount remaining/current value in USD', max_digits=20)),
                ('pnl', models.DecimalField(decimal_places=2, help_text='Profit and Loss in USD', max_digits=20)),
                ('oppositeoutcome', models.CharField(help_text='The opposite outcome option', max_length=100)),
                ('title', models.CharField(help_text='Market/position title', max_length=500)),
                ('negativerisk', models.BooleanField(default=False, help_text='Whether this is a negative risk position')),
                ('marketsid', models.ForeignKey(db_column='marketsid', help_text='Market this position belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='markets.market')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'positions',
                'ordering': ['-positionid'],
                'indexes': [models.Index(fields=['marketsid', 'walletid'], name='positions_markets_aa288f_idx'), models.Index(fields=['walletid', 'positionstatus'], name='positions_walleti_8bc76a_idx'), models.Index(fields=['positionstatus'], name='positions_positio_51608e_idx'), models.Index(fields=['outcome'], name='positions_outcome_542f85_idx')],
            },
        ),
    ]
