# Generated by Django 5.2.8 on 2025-11-25 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('positionid', models.BigAutoField(primary_key=True, serialize=False)),
                ('conditionid', models.CharField(db_index=True, default='', help_text='Platform market ID (condition ID from Polymarket)', max_length=255)),
                ('outcome', models.CharField(help_text='Predicted outcome (Yes/No/etc.)', max_length=100)),
                ('oppositeoutcome', models.CharField(help_text='The opposite outcome option', max_length=100)),
                ('title', models.CharField(help_text='Market/position title', max_length=500)),
                ('positionstatus', models.SmallIntegerField(choices=[(1, 'OPEN'), (2, 'CLOSED')], db_index=True, help_text='Position status (1=open, 2=closed)')),
                ('tradestatus', models.SmallIntegerField(choices=[(1, 'NEED_TO_PULL_TRADES'), (2, 'POSITION_CLOSED')], db_index=True, default=1, help_text='Trade fetch status')),
                ('totalshares', models.DecimalField(decimal_places=6, help_text='Total shares from API (current position)', max_digits=20)),
                ('currentshares', models.DecimalField(decimal_places=6, default=0, help_text='Current shares held (same as totalshares for open)', max_digits=20)),
                ('averageentryprice', models.DecimalField(decimal_places=6, help_text='Average entry price per share', max_digits=10)),
                ('amountspent', models.DecimalField(decimal_places=2, help_text='Invested amount from API (totalBought * avgPrice)', max_digits=20)),
                ('amountremaining', models.DecimalField(decimal_places=2, help_text='Current value from API (currentValue for open, 0 for closed)', max_digits=20)),
                ('calculatedamountinvested', models.DecimalField(decimal_places=2, default=0, help_text='Market-wise invested amount calculated from trades', max_digits=20)),
                ('calculatedcurrentvalue', models.DecimalField(decimal_places=2, default=0, help_text='Market-wise current value calculated from trades', max_digits=20)),
                ('calculatedamountout', models.DecimalField(decimal_places=2, default=0, help_text='Market-wise amount taken out calculated from trades', max_digits=20)),
                ('realizedpnl', models.DecimalField(decimal_places=2, default=0, help_text='Market-wise realized PNL', max_digits=20)),
                ('unrealizedpnl', models.DecimalField(decimal_places=2, default=0, help_text='Market-wise unrealized PNL', max_digits=20)),
                ('apirealizedpnl', models.DecimalField(blank=True, decimal_places=2, help_text='Realized PNL from API (for closed positions)', max_digits=20, null=True)),
                ('enddate', models.DateTimeField(blank=True, help_text='Position/market end date', null=True)),
                ('negativerisk', models.BooleanField(default=False, help_text='Whether this is a negative risk position')),
                ('createdat', models.DateTimeField(auto_now_add=True, help_text='When record was created', null=True)),
                ('lastupdatedat', models.DateTimeField(auto_now=True, help_text='Last update timestamp', null=True)),
                ('marketsid', models.ForeignKey(db_column='marketsid', help_text='Market this position belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='markets.market')),
                ('walletsid', models.ForeignKey(blank=True, db_column='walletsid', help_text='Wallet that holds this position', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'positions',
                'ordering': ['-lastupdatedat'],
                'indexes': [models.Index(fields=['walletsid', 'marketsid'], name='positions_wallets_4bdfa9_idx'), models.Index(fields=['walletsid', 'positionstatus'], name='positions_wallets_db0f07_idx'), models.Index(fields=['positionstatus'], name='positions_positio_51608e_idx'), models.Index(fields=['tradestatus'], name='positions_tradest_285ae2_idx'), models.Index(fields=['conditionid'], name='positions_conditi_b69cab_idx'), models.Index(fields=['outcome'], name='positions_outcome_542f85_idx')],
                'unique_together': {('walletsid', 'marketsid', 'outcome')},
            },
        ),
    ]
