# Generated by Django 5.2.8 on 2025-11-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='tradestatus',
            field=models.SmallIntegerField(choices=[(1, 'NEED_TO_PULL_TRADES'), (2, 'POSITION_CLOSED'), (3, 'POSITION_CLOSED_NEED_DATA')], db_index=True, default=1, help_text='Trade fetch status'),
        ),
    ]
