# Generated by Django 5.2.8 on 2025-11-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('positions', '0001_initial'),
        ('wallets', '0004_add_wallettype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-lastupdatedat'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='positions_markets_aa288f_idx',
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='positions_walleti_8bc76a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('walletsid', 'marketsid', 'outcome')},
        ),
        migrations.AddField(
            model_name='position',
            name='apirealizedpnl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Realized PNL from API (for closed positions)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='calculatedamountinvested',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Market-wise invested amount calculated from trades', max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='calculatedamountout',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Market-wise amount taken out calculated from trades', max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='calculatedcurrentvalue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Market-wise current value calculated from trades', max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='conditionid',
            field=models.CharField(db_index=True, default='', help_text='Platform market ID (condition ID from Polymarket)', max_length=255),
        ),
        migrations.AddField(
            model_name='position',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, help_text='When record was created', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='currentshares',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Current shares held (same as totalshares for open)', max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='enddate',
            field=models.DateTimeField(blank=True, help_text='Position/market end date', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='lastupdatedat',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='realizedpnl',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Market-wise realized PNL', max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='tradestatus',
            field=models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'NEED_TO_PULL_TRADES'), (3, 'TRADES_PULLED'), (4, 'POSITION_CLOSED_NEED_DATA'), (5, 'ERROR')], db_index=True, default=1, help_text='Trade fetch status'),
        ),
        migrations.AddField(
            model_name='position',
            name='unrealizedpnl',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Market-wise unrealized PNL', max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='walletsid',
            field=models.ForeignKey(blank=True, db_column='walletsid', help_text='Wallet that holds this position', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='wallets.wallet'),
        ),
        migrations.AlterField(
            model_name='position',
            name='amountremaining',
            field=models.DecimalField(decimal_places=2, help_text='Current value from API (currentValue for open, 0 for closed)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='amountspent',
            field=models.DecimalField(decimal_places=2, help_text='Invested amount from API (totalBought * avgPrice)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='positionstatus',
            field=models.SmallIntegerField(choices=[(1, 'CLOSED'), (2, 'OPEN')], db_index=True, help_text='Position status (1=open, 2=closed)'),
        ),
        migrations.AlterField(
            model_name='position',
            name='totalshares',
            field=models.DecimalField(decimal_places=6, help_text='Total shares from API (current position)', max_digits=20),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['walletsid', 'marketsid'], name='positions_wallets_4bdfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['walletsid', 'positionstatus'], name='positions_wallets_db0f07_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['tradestatus'], name='positions_tradest_285ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['conditionid'], name='positions_conditi_b69cab_idx'),
        ),
        migrations.RemoveField(
            model_name='position',
            name='amounttakenout',
        ),
        migrations.RemoveField(
            model_name='position',
            name='pnl',
        ),
        migrations.RemoveField(
            model_name='position',
            name='walletid',
        ),
    ]
