# Generated by Django 5.2.8 on 2025-12-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_alter_position_tradestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='positionstatus',
            field=models.SmallIntegerField(choices=[(1, 'OPEN'), (2, 'CLOSED'), (3, 'CLOSED_NEED_DATA')], db_index=True, help_text='Position status (1=open, 2=closed)'),
        ),
        migrations.AlterField(
            model_name='position',
            name='tradestatus',
            field=models.SmallIntegerField(choices=[(1, 'NEED_TO_PULL_TRADES'), (2, 'NEED_TO_CALCULATE_PNL'), (3, 'TRADES_SYNCED')], db_index=True, default=1, help_text='Trade fetch status'),
        ),
    ]
