# Generated by Django 5.2.8 on 2025-11-12 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletsid', models.AutoField(primary_key=True, serialize=False)),
                ('proxywallet', models.CharField(db_index=True, help_text='Blockchain wallet address', max_length=255, unique=True)),
                ('username', models.CharField(db_index=True, help_text='Display name of wallet owner', max_length=255)),
                ('xusername', models.CharField(blank=True, help_text='Twitter/X handle', max_length=255, null=True)),
                ('verifiedbadge', models.BooleanField(blank=True, default=False, help_text='Whether user has verified badge', null=True)),
                ('profileimage', models.CharField(blank=True, help_text='URL to profile image', max_length=500, null=True)),
                ('isactive', models.SmallIntegerField(default=1, help_text='0=inactive, 1=active')),
                ('platform', models.CharField(db_index=True, default='polymarket', help_text='Trading platform (polymarket, etc.)', max_length=50)),
                ('firstseenat', models.DateTimeField(default=django.utils.timezone.now, help_text='When wallet was first discovered')),
                ('lastupdatedat', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets',
                'ordering': ['-lastupdatedat'],
                'indexes': [models.Index(fields=['proxywallet'], name='wallets_proxywa_731eab_idx'), models.Index(fields=['username'], name='wallets_usernam_fc589a_idx'), models.Index(fields=['isactive', 'platform'], name='wallets_isactiv_bddb83_idx')],
            },
        ),
    ]
