# Generated by Django 5.2.8 on 2025-11-12 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletCategoryStat',
            fields=[
                ('statid', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, help_text='Market category (Politics, Sports, Crypto, etc.)', max_length=100)),
                ('timeperiod', models.CharField(db_index=True, help_text='Time period (7d, 30d, 90d, all-time)', max_length=20)),
                ('rank', models.SmallIntegerField(help_text='Rank in this category for this time period')),
                ('volume', models.DecimalField(decimal_places=2, help_text='Trading volume in USD', max_digits=20)),
                ('pnl', models.DecimalField(decimal_places=2, help_text='Profit and Loss in USD', max_digits=20)),
                ('snapshottime', models.DateTimeField(db_index=True, help_text='When this snapshot was taken')),
                ('createdat', models.DateTimeField(auto_now_add=True, help_text='When record was created')),
                ('lastupdatedat', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('wallets', models.ForeignKey(db_column='walletsid', help_text='Wallet this stat belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='category_stats', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Category Stat',
                'verbose_name_plural': 'Wallet Category Stats',
                'db_table': 'walletcategorystats',
                'ordering': ['-snapshottime', 'rank'],
                'indexes': [models.Index(fields=['wallets', 'category', 'timeperiod'], name='walletcateg_wallets_b4f62b_idx'), models.Index(fields=['category', 'timeperiod', 'rank'], name='walletcateg_categor_d2fc39_idx'), models.Index(fields=['snapshottime'], name='walletcateg_snapsho_9e1fd0_idx')],
                'unique_together': {('wallets', 'category', 'timeperiod', 'snapshottime')},
            },
        ),
    ]
