# Generated by Django 5.2.8 on 2025-11-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_walletcategorystat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='walletcategorystat',
            unique_together={('wallets', 'category', 'timeperiod')},
        ),
    ]
